<?php
class Mercuriel_Autofill_Block_Adminhtml_Autofill_Grid extends Mage_Adminhtml_Block_Widget_Grid
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setId('autofillGrid');
        $this->setDefaultSort('autofill_group_id');
        $this->setDefaultDir('DESC');
        $this->setSaveParametersInSession(true);
    }
    public function _prepareColumns()
    {
        $this->addColumn('autofill_group_id', array(
            'header'    => Mage::helper('mercuriel_autofill')->__('Autofill Group ID'),
            'width'     => '50px',
            'index'     => 'autofill_group_id',
            'sortable'  => 'true'
        ));
        $this->addColumn('attribute_group_id', array(
            'header'    => Mage::helper('mercuriel_autofill')->__('Attribute Group ID'),
            'width'     => '50px',
            'index'     => 'attribute_group_id',
            'sortable'  => 'true'
        ));
        $this->addColumn('attribute_group_name', array(
            'header'    => Mage::helper('mercuriel_autofill')->__('Attribute Group Name'),
            'width'     => '50px',
            'index'     => 'attribute_group_name',
            'sortable'  => 'true'
        ));
        $this->addColumn('attribute_set_name', array(
        'header'    => Mage::helper('mercuriel_autofill')->__('Attribute Set Name'),
        'width'     => '50px',
        'index'     => 'attribute_set_name',
        'sortable'  => 'true'
         ));

        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }
    public function _prepareCollection()
    {
        $collection = Mage::getResourceModel('mercuriel_autofill/autofillGroup_collection');
        //Join to add information field from other table
        $collection->getSelect()->join('eav_attribute_group',
            'eav_attribute_group.attribute_group_id = main_table.attribute_group_id', array('attribute_group_name','attribute_set_id'))
        ->join('eav_attribute_set',
            'eav_attribute_set.attribute_set_id = eav_attribute_group.attribute_set_id', array('attribute_set_name'));

        $this->setCollection($collection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    public function _prepareMassaction()
    {
        $this->setMassactionIdField('autofill_group_id');
        $this->getMassactionBlock()->setFormFieldName('autofill');

        $this->getMassactionBlock()->addItem('delete', array(
            'label'     => Mage::helper('mercuriel_autofill')->__('Delete'),
            'url'       => $this->getUrl('*/*/massDelete'),
            'confirm'   => Mage::helper('mercuriel_autofill')->__('Are you sure?')
        ));
        return parent::_prepareMassaction(); // TODO: Change the autogenerated stub
    }
    public function getRowUrl($item)
    {
        return $this->geturl('*/*/edit', array('id' => $item->getAutofillGroupId())); // TODO: Change the autogenerated stub
    }
}