<?php
class Mercuriel_Autofill_Block_Adminhtml_Autofill_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{
    public function _prepareForm()
    {
        $form = new Varien_Data_Form(array(
            'id'        => 'edit_form',
            'action'    => $this->getUrl('*/*/save', array('id', $this->getRequest()->getParam('id'))),
            'method'    => 'post',
            'enctype'   => 'multipart/form-data'
        ));
        $form->setUseContainer(true);
        $this->setForm($form);
        if(Mage::getSingleton('adminhtml/session')->getFormData()){
            $data = Mage::getSingleton('adminhtml/session')->getFormData();
            Mage::getSingleton('adminhtml/session')->setFormData(null);
        }
        elseif(Mage::registry('autofill_data')){
            $data = Mage::registry('autofill_data')->getData();
        }
        $fieldset = $form->addFieldset('autofill_form', array(
            'legend' => Mage::helper('mercuriel_autofill')->__('Autofill Group Information')
        ));
        $fieldset->addField('autofill_group_id', 'text', array(
            'label' => Mage::helper('mercuriel_autofill')->__('Autofill Group Id'),
            'class' => 'required-entry',
            'required'  => true,
            'name'      => 'autofill_group_id',
        ));
        $fieldset->addField('attribute_group_id', 'text', array(
            'label' => Mage::helper('mercuriel_autofill')->__('Attribute Group Id'),
            'class' => 'required-entry',
            'required'  => true,
            'name'      => 'attribute_group_id'
        ));
        $fieldset->addField('attribute_group_name', 'text', array(
            'label' => Mage::helper('mercuriel_autofill')->__('Attribute Group Name'),
            'class' => 'required-entry disabled',
            'disabled'=> true,
            'name'      => 'attribute_group_name'
        ));
        $fieldset->addField('attribute_set_name', 'text', array(
            'label' => Mage::helper('mercuriel_autofill')->__('Attribute Set Name'),
            'class' => 'required-entry disabled',
            'disabled'=> true,
            'name'      => 'attribute_set_name'
        ));
        
        $fieldset1 = $form->addFieldset('autofill_value', array(
            'legend' => Mage::helper('mercuriel_autofill')->__("Autofill Group Value")
        ));

        // for loop here to add the attribute one by one
        $form->setValues($data);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}